# Generated by Django 4.2.1 on 2023-06-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djrep', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reptiletraining',
            name='params',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reptiletraining',
            name='type',
            field=models.CharField(choices=[('Sine', 'Sine Example')], default='Sine', max_length=20),
            preserve_default=False,
        ),
    ]
