# Generated by Django 4.2.1 on 2023-06-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djrep', '0002_reptiletraining_params_reptiletraining_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reptiletraining',
            name='data_file',
            field=models.FileField(blank=True, null=True, upload_to='training_sources'),
        ),
    ]
