# Generated by Django 4.2.1 on 2023-06-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djrep', '0003_reptiletraining_data_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='reptiletraining',
            name='status',
            field=models.CharField(default='Waiting to start', max_length=100),
        ),
        migrations.AddField(
            model_name='reptiletraining',
            name='status_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
