# Generated by Django 4.2.1 on 2023-06-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djrep', '0005_remove_reptiletraining_data_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reptiletraining',
            name='type',
            field=models.CharField(choices=[('DataFile', 'Data File'), ('Sine', 'Sine Example')], max_length=20),
        ),
    ]
